apiVersion: v1
kind: Namespace
metadata:
  name: sascha-kohler-coaching
---
apiVersion: v1
kind: Secret
metadata:
  name: coaching-site-secrets
  namespace: sascha-kohler-coaching
type: Opaque
stringData:
  MAKE_CONTACT_WEBHOOK_URL: "https://hook.eu2.make.com/lcovnsx4lhuhtr5vvjdfw0u1jihiyk77"
  # NEXT_PUBLIC_MAKE_CONTACT_WEBHOOK_URL: "https://hook.eu2.make.com/lcovnsx4lhuhtr5vvjdfw0u1jihiyk77"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sascha-kohler-coaching-site
  namespace: sascha-kohler-coaching
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sascha-kohler-coaching-site
  template:
    metadata:
      labels:
        app: sascha-kohler-coaching-site
    spec:
      containers:
        - name: website
          image: blisha234/sascha-kohler-coaching:latest
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_SITE_URL
              value: "https://sascha-kohler.at"
            - name: MAKE_CONTACT_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: coaching-site-secrets
                  key: MAKE_CONTACT_WEBHOOK_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: cache-volume
              mountPath: /app/.next/cache
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sascha-kohler-coaching-site
  namespace: sascha-kohler-coaching
spec:
  selector:
    app: sascha-kohler-coaching-site
  ports:
    - port: 80
      name: http
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sascha-kohler-coaching-site
  namespace: sascha-kohler-coaching
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-XSS-Protection "1; mode=block" always;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sascha-kohler.at
        - www.sascha-kohler.at
      secretName: sascha-kohler-at-tls
  rules:
    - host: sascha-kohler.at
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sascha-kohler-coaching-site
                port:
                  number: 80
    - host: www.sascha-kohler.at
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sascha-kohler-coaching-site
                port:
                  number: 80
