name: Docker Build and Push

on:
  push:
    branches: [main]
    # Nur bestimmte Dateien auslösen
    paths:
      - 'src/**'
      - 'public/**'
      - 'content/**'
      - 'package*.json'
      - 'Dockerfile'
      - 'next.config.js'
      - 'mdx-components.tsx'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image variables
        id: image-vars
        run: |
          IMAGE="blisha234/sascha-kohler-coaching"
          TAG="${GITHUB_SHA::7}"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "image_with_tag=$IMAGE:$TAG" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.image-vars.outputs.image_with_tag }}
            ${{ steps.image-vars.outputs.image }}:latest
          cache-from: type=registry,ref=blisha234/sascha-kohler-coaching:buildcache
          cache-to: type=registry,ref=blisha234/sascha-kohler-coaching:buildcache,mode=max
          build-args: |
            NEXT_PUBLIC_CONTACT_FORM_ENDPOINT=${{ secrets.NEXT_PUBLIC_CONTACT_FORM_ENDPOINT }}

      - name: Set up kubectl
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG_DATA" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Update Kubernetes deployment image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          kubectl set image deployment/sascha-kohler-website website=${{ steps.image-vars.outputs.image_with_tag }} --namespace sascha-kohler-at

      - name: Verify rollout status
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          kubectl rollout status deployment/sascha-kohler-website --namespace sascha-kohler-at